import pandas as pd
import matplotlib.pyplot as plt

# Load the CSV file generated by your code
df = pd.read_csv("output_resample_filter/Sub_9_0_resample.csv")

# Calculate time in seconds
frame_rate = 1 # frames per second
df['Time'] = df.index / frame_rate

# Create figure with a wider width and axis objects
fig, ax1 = plt.subplots(figsize=(16, 8))  # Adjust width and height as needed

# Plot both AC_red and SPO2 on the same y-axis
color1 = 'tab:red'
color2 = 'tab:blue'
ax1.set_xlabel('Time (seconds)')
ax1.set_ylabel('Pridict_SPO2', color="black")
ax1.plot(df['Time'], df['Pridict_SPO2'], label='Pridict_SPO2', color=color1)
ax1.tick_params(axis='y', labelcolor="black")

ax2 = ax1.twinx()
ax2.set_ylabel('SPO2 (%)', color="black")
ax2.plot(df['Time'], df['SPO2'], label='SPO2_GT', color=color2)
ax2.tick_params(axis='y', labelcolor="black")

# Add title and legend
plt.title('Pridict_SPO2 and SPO2_GT')
fig.tight_layout() 
fig.legend(loc="lower right")
plt.show()
