import pandas as pd
import matplotlib.pyplot as plt
from scipy.signal import find_peaks

# Load the CSV file generated by your code
df = pd.read_csv("output_resample_filter/Sub_9_0_resample.csv")
# df = pd.read_csv("Sub22-2_resampled.csv")

# Calculate time in seconds
frame_rate = 30  # frames per second
df['Time'] = df.index / frame_rate

# Create figure and axis objects
fig, ax1 = plt.subplots()

# Plot RR on the primary y-axis
color = 'tab:red'
ax1.set_xlabel('Frame Count')
ax1.set_ylabel('Respiratory Rate', color='black')
ax1.plot(df.index, df['AC_red'], label='AC_red', color=color)
ax1.tick_params(axis='y', labelcolor='black')

# Create secondary y-axis for SPO2
ax2 = ax1.twinx()  
color = 'tab:blue'
ax2.set_ylabel('Oxygen Saturation', color=color)
ax2.plot(df.index, df['SPO2'], label='SPO2', color=color)
ax2.tick_params(axis='y', labelcolor=color)

# Add title and legend
plt.title('Respiratory Rate vs Oxygen Saturation')
fig.tight_layout() 
plt.show()
