import pandas as pd
import matplotlib.pyplot as plt
from scipy.signal import find_peaks

# Load the CSV file generated by your code
df = pd.read_csv("./video_output2/p2_v1_source1_output.csv")

# Calculate time in seconds
frame_rate = 30  # frames per second
df['Time'] = df.index / frame_rate

# Plot DC signal
# plt.plot(df['PR_normalized'], label='PR_normalized')


# plt.plot(df['B_normalized'], label='B_normalized')
# plt.plot(df['G_normalized'], label='G_normalized')
# plt.plot(df['R_normalized'], label='R_normalized')
# plt.plot(df['Time'], df['PR_normalized'], label='PR_normalized')
# plt.plot(df['PR_filtered'], label='PR_filtered')
# plt.plot(df['fir_filtered'], label='fir_filtered')
# plt.plot(df['Time'], df['fir_filtered'], label='fir_filtered')

plt.plot(df['R'], label='R', color='red')
# plt.plot(df['DC_red'], label='DC_red')
# plt.plot(df['DC_red_filter'], label='DC_red_filter')

# plt.plot(df['G'], label='G', color='green')
# plt.plot(df['DC_green'], label='DC_green')

# plt.plot(df['B'], label='B', color='blue')
# plt.plot(df['DC_blue'], label='DC_blue')
# plt.plot(df['DC_blue_filter'], label='DC_blue_filter')
#######################################################

# plt.plot(df['AC_red'], label='AC_red')
# plt.plot(df['AC_red_filtered'], label='AC_red_filtered')

# plt.plot(df['AC_blue'], label='AC_blue')
# plt.plot(df['AC_blue_filtered'], label='AC_blue_filtered')

# plt.plot(df['AC_green'], label='AC_green')
# plt.plot(df['AC_green_filtered'], label='AC_green_filtered')

# plt.plot(df['RR'], label='RR')

# plt.plot(df['SPO2'], label='SPO2', color='blue')

# Customize plot
plt.xlabel('Time Count')
plt.ylabel('Color Value')
# plt.title('R and DC_red')
# plt.title('G and DC_green')
# plt.title('B and DC_blue')

# plt.title('AC_red')
# plt.title('AC_blue')
# plt.title('AC_green')
# plt.title('')
plt.legend()
plt.show()
