import pandas as pd

# Load the CSV file generated by your code
df = pd.read_csv("Sub21-1.csv")

# Calculate time in seconds
frame_rate = 30  # frames per second
df['Time'] = df.index / frame_rate

# Convert index to datetime
df.index = pd.to_datetime(df['Time'], unit='s')



# Resample RR every 1 second and take the mean
df_rr_resampled = df['RR'].resample('1s').mean().reset_index()  # 's' instead of 'S'

# Save the resampled data to a new CSV file
df_resampled = pd.concat([ df_rr_resampled['RR']], axis=1)
df_resampled.to_csv("Sub21-1_resampled.csv", index=False)
